<?php

namespace common\models;

use yii\mongodb\ActiveRecord;

class View extends ActiveRecord
{
    /**
     * @return string the name of the index associated with this ActiveRecord class.
     */
    public static function collectionName()
    {
        return 'View';
    }
    /**
     * @return array list of attribute names.
     */
    public function attributes()
    {
        return ['_id', 'post_id', 'view_num'];
    }

    public function getPost()
    {
        return $this->hasOne(Make::className(), ['id' => 'post_id']);
    }

    public function beforeSave($insert)
    {
        $this->post_id = (int)$this->post_id ;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }



}